### PR TITLE
FRU list appears to have extraneous data in output

### PR DESCRIPTION
**Pull request by rjknight**
-Update membuf fru id to point to a separate fru inventory
     record so that all the data fits correcty in a single record.

### CODE REVIEW

**Comment by rjknight** [comment]
@bwmashak, @wghoffa please take a look at the updates.

**Comment by bwmashak** [comment]
Why can't the FRU ID = 2 be maintained for Membuf?  I was thinking FRU ID = 42 would just be overflow for Membuf ECID, but all backplane components would still callout the main backplane, FRU ID = 2.

**Comment by wghoffa** [comment]
I didn't think that is what we discussed on the phone @bwmashak. I thought we wanted the Backplane to be ID 2 as it contained all of the PN/SN etc. information and it would be found next to all of the records with similar information and the ECID data would slide to the end as less people are interested in that information.

**Comment by rjknight** [comment]
I switched them to 42 so that the fru collection would work, if we remove the ecids from the backplane fru info then need a way to collect that info that works for all platforms,   I was expecting AMI to use 2  for the entity Id to fru correlation, but they could use 42, it doesn't matter

**Comment by rjknight** [comment]
Cancelling this pull request. I talked to Ben, we want to maintain FRU_ID 2 as the data AMI uses to indicate the failing fru in a sel, however we still need to pass the ecid data and have it associated with fru_id 42, will need to update hostboot code to support logical and actual fru ids.

**Pull request closed without merging**
